//import 'babel/register'
import React, { Component } from 'react'

React.initializeTouchEvents(true)

import Main from './pages/main/main'

import logoPNG from '../images/react-mirror.png'
import headerPNG from '../images/header.png'
import mirrorsPNG from '../images/mirrors.png'

const displayName = 'App'

class App extends Component {

  render () {

    return (
      <div id='container'>
        <div className='inner'>
          <header style={{ marginLeft: 160, position: 'relative', overflow: 'visible', marginBottom: '-80px' }}>
            <img src={ logoPNG } alt='react-mirror' title='react-mirror' />
            <h2 style={{ textIndent: '10%', fontSize: '1.2em', marginLeft: 10, height: 72 }}>
              <img src={ headerPNG } alt='header' title='Fully synchronized replicas from any react component.' />
            </h2>
            <h2 style={{ fontSize: '1.05em', marginRight: 20, textAlign: 'right', letterSpacing: '0.01em' }}>
              Besides, you can remove all replicas of a mirrored component, which will detach all nodes from that component from the DOM but
              as long as you keep a reference to its surface, it can be replicated again as if it was never gone.
            </h2>
          </header>
          <section id='downloads' className='clearfix' style={{ float: 'right', position: 'relative', top: '-142px', left: '-42px' }}>
            <a href='https://github.com/Theadd/react-mirror' id='view-on-github' className='button'><span>View on GitHub</span></a>
          </section>
          <div style={{ float: 'none', clear: 'both' }} />
          <div style={{ position: 'absolute', height: 0, overflow: 'visible', float: 'left', marginTop: '-103px', marginLeft: '-74px', zIndex: 1 }}>
            <img src={ mirrorsPNG } alt='mirrors' />
          </div>
          <section id="main_content">
            <Main />
          </section>
          <footer>
            react-mirror is maintained by <a href='https://github.com/Theadd'>Theadd</a><br />
            This page was generated by <a href='https://pages.github.com'>GitHub Pages</a>. Tactile theme by <a href='https://twitter.com/jasonlong'>Jason Long</a>.
          </footer>
        </div>
      </div>
    )
  }
}

App.displayName = displayName

React.render(<App />, document.getElementById('root'))

//TODO: remove

var gBabel = require("babel-core/browser");

window._gBabel = gBabel;