//import 'babel/register'
import React, { Component } from 'react'

React.initializeTouchEvents(true)

import Main from './pages/main/main'
import Sketch from './pages/sketch/sketch'
import FitterHappierText from 'react-fitter-happier-text'

import logoPNG from '../images/react-mirror.png'
import mirrorsPNG from '../images/mirrors.png'

import './main.css'

const displayName = 'App'
const pages = new Map([['', Main], ['#sketch', Sketch]])

class App extends Component {

  constructor (props) {
    super(props)
    !pages.has(window.location.hash) && (window.location.hash = '')

    window.onhashchange = this.handleHashChange.bind(this)
    this.state = {
      Page: pages.get(window.location.hash)
    }
  }

  handleHashChange () {
    !pages.has(window.location.hash) && (window.location.hash = '')
    this.setState({
      Page: pages.get(window.location.hash)
    })
  }

  render () {
    const { Page } = this.state

    return (
      <div id='container'>
        <div className='inner'>
          <header style={{ marginLeft: 160, position: 'relative', overflow: 'visible', marginBottom: '-80px' }}>
            <img src={ logoPNG } alt='react-mirror' title='react-mirror' />
            <div className='header-svg-text'>
              <FitterHappierText text={ `Takes control of component's rendering cycle` } />
              <FitterHappierText text={ `allowing many synchronized replicas of it's DOM` } />
            </div>
            <h2 style={{ fontSize: '1.05em', marginRight: 20, textAlign: 'right', letterSpacing: '0.01em' }}>
              Besides, you can remove all replicas of a mirrored component, which will detach all nodes from that component from the DOM but
              as long as you keep a reference to its surface, it can be replicated again as if it was never gone.
            </h2>
          </header>
          <section id='downloads' className='clearfix' style={{ float: 'right', position: 'relative', top: '-142px', left: '-42px' }}>
            <a href='https://github.com/Theadd/react-mirror' id='view-on-github' className='button'><span>View on GitHub</span></a>
          </section>
          <div style={{ float: 'none', clear: 'both' }} />
          { window.location.hash === '' ? <div style={{ position: 'absolute', height: 0, overflow: 'visible', float: 'left', marginTop: '-103px', marginLeft: '-74px', zIndex: 1 }}>
            <img src={ mirrorsPNG } alt='mirrors' />
          </div> : null }
          <section id="main_content">
            <Page />
          </section>
          <footer>
            react-mirror is maintained by <a href='https://github.com/Theadd'>Theadd</a><br />
            This page was generated by <a href='https://pages.github.com'>GitHub Pages</a>. Tactile theme by <a href='https://twitter.com/jasonlong'>Jason Long</a>.
          </footer>
        </div>
      </div>
    )
  }
}

App.displayName = displayName

React.render(<App />, document.getElementById('root'))
